# Generated by Django 5.0.4 on 2024-04-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_attendance_date_came_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_came',
            field=models.DateField(blank=True, null=True),
        ),
    ]
